version: '2.2'
services:
  php-apache-environment:
    image: vinkaamalia/uas
    container_name: php-apache
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80
    networks:
      - backend

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE:  dbperpus
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./dbperpus.sql:/docker-entrypoint-initdb.d/dbperpus.sql
    networks:
      - backend

volumes:
  db:

networks:
  backend:
    name: backend-network
    ipam:
      driver: default
      config:
        - subnet : 172.20.0.0/24
